project:
  name: qs-eks
  regions:
  - ap-southeast-1
  - us-east-1
  - us-west-2
  - eu-central-1
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-west-1
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: arniesaha@gmail.com
      KeyPairName: eks
      RemoteAccessCIDR: "0.0.0.0/0"
      WebserverCIDR: "0.0.0.0/0"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "$[taskcat_current_region]"